version: "3.2"

services:
  LiCalendar:
    image: 'hslr/li-calendar:latest'
    container_name: LiCalendar
    volumes:
      - ./conf:/app/conf
      - ./uploads:/app/uploads
      - ./database:/app/database

    # environment:
    #   - TZ=Asia/Shanghai # 设置中国上海时区
    
    ports:
      - 9090:9090
    restart: always